Task - 1

In [ ]:
4.1 Exercise on Functions:

In [ ]:
def convert_units(choice, option, value):
    """
    Converts units based on user choice.

    Parameters:
    choice (str): User’s conversion category
    option (str): Selected conversion option
    value (float): Number to be converted

    Returns:
    float: Converted value
    """

    # Length
    if choice == "1":
        if option == "1":
            return value * 3.28084
        elif option == "2":
            return value / 3.28084

    # Weight
    elif choice == "2":
        if option == "1":
            return value * 2.20462
        elif option == "2":
            return value / 2.20462

    # Volume
    elif choice == "3":
        if option == "1":
            return value * 0.264172
        elif option == "2":
            return value / 0.264172


print("Choose conversion type:")
print("1. Length")
print("2. Weight")
print("3. Volume")

choice = input("Enter your choice (1/2/3): ")

try:
    value = float(input("Enter the value to convert: "))

    if choice == "1":
        print("1. Meters to Feet")
        print("2. Feet to Meters")

    elif choice == "2":
        print("1. Kilograms to Pounds")
        print("2. Pounds to Kilograms")

    elif choice == "3":
        print("1. Liters to Gallons")
        print("2. Gallons to Liters")

    option = input("Choose option: ")

    result = convert_units(choice, option, value)

    print("Converted value:", result)

except ValueError:
    print("Error: Please enter a valid number.")

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter your choice (1/2/3): 3
Enter the value to convert: 45
1. Liters to Gallons
2. Gallons to Liters
Choose option: 2
Converted value: 170.34356404160926


Task 2

In [ ]:
def find_sum(numbers):
    """
    Calculates the sum of numbers in a list.

    Parameters:
    numbers (list): A list containing numbers.

    Returns:
    float: The total sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of numbers in a list.

    Parameters:
    numbers (list): List of values.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers (list): List of numbers.

    Returns:
    float: Maximum value in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers (list): List of numbers.

    Returns:
    float: Minimum value in the list.
    """
    return min(numbers)


print("Choose an operation:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

choice = input("Enter your choice (1/2/3/4): ")

try:
    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("List cannot be empty")

    if choice == "1":
        result = find_sum(numbers)
    elif choice == "2":
        result = find_average(numbers)
    elif choice == "3":
        result = find_max(numbers)
    elif choice == "4":
        result = find_min(numbers)
    else:
        print("Invalid operation")
        exit()

    print("Result:", result)

except ValueError:
    print("Error: Please enter valid numbers.")

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 2
Enter numbers separated by spaces: 2 3
Result: 2.5


4.2 Exercise on List Manipulation

In [ ]:
#Task 1: Extract Every Other Element
def extract_every_other(lst):
    return lst[::2]

numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


In [ ]:
#Task 2: Slice a Sublist
def get_sublist(lst, start, end):
    return lst[start:end+1]
numbers = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(numbers, 2, 4)
print(sublist)

[3, 4, 5]


In [ ]:
#Task 3: Reverse a List Using Slicing
def reverse_list(lst):
    return lst[::-1]
numbers = [1, 2, 3, 4, 5]
reversed_numbers = reverse_list(numbers)
print(reversed_numbers)

[5, 4, 3, 2, 1]


In [ ]:
#Task 4: Remove the First and Last Elements
def remove_first_last(lst):
    return lst[1:-1]
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


In [ ]:
#Task 5: Get the First n Elements
def get_first_n(lst, n):
    return lst[:n]
numbers = [1, 2, 3, 4, 5]
first_three = get_first_n(numbers, 3)
print(first_three)

[1, 2, 3]


In [ ]:
#Task 6: Extract Elements from the End
def get_last_n(lst, n):
    return lst[-n:]
numbers = [1, 2, 3, 4, 5]
last_two = get_last_n(numbers, 2)
print(last_two)

[4, 5]


In [ ]:
#Task 7: Extract Elements in Reverse Order
def reverse_skip(lst):
    return lst[-2::-2]
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)

[5, 3, 1]


4.3 Exercise on Nested List:

In [ ]:
#Task 1: Flatten a Nested List
def flatten(lst):
    flat_list = []
    for sublist in lst:
        flat_list.extend(sublist)
    return flat_list
nested = [[1, 2], [3, 4], [5]]
flat = flatten(nested)
print(flat)

[1, 2, 3, 4, 5]


In [ ]:
#Task 2: Accessing Nested List Elements
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)

6


In [ ]:
#Task 3: Sum of All Elements in a Nested List
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total
nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)

21


In [ ]:
#Task 4: Remove Specific Element from a Nested List
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)
    return result
nested_list = [[1, 2], [3, 2], [4, 5]]
elem_to_remove = 2
new_list = remove_element(nested_list, elem_to_remove)
print(new_list)

[[1], [3], [4, 5]]


In [ ]:
#Task 5: Find the Maximum Element in a Nested List
def find_max(lst):
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

6


In [ ]:
#Task 6: Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count
nested_list = [[1, 2], [2, 3], [2, 4]]
elem_to_count = 2
result = count_occurrences(nested_list, elem_to_count)
print(result)

3


In [ ]:
#Task 7: Flatten a List of Lists of Lists
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#Task 8: Nested List Average
def average_nested(lst):
    def flatten_and_sum(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                sub_total, sub_count = flatten_and_sum(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = flatten_and_sum(lst)
    return total_sum / total_count if total_count != 0 else 0
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5


10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np

In [ ]:
#task 1
empty_array = np.empty((2, 2))
print(empty_array)

[[2.55174188e-315 0.00000000e+000]
 [2.41907520e-312 5.68175493e-322]]


In [ ]:
#task 2
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#task 3
filled_array = np.full((3, 3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#task 4
original_array = np.array([[5, 7], [2, 9]])
zeros_like_array = np.zeros_like(original_array)
print(zeros_like_array)

[[0 0]
 [0 0]]


In [ ]:
#task 5
original_array = np.array([[5, 7], [2, 9]])
ones_like_array = np.ones_like(original_array)
print(ones_like_array)

[[1 1]
 [1 1]]


In [ ]:
#task 6
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print(array_from_list)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [ ]:
#task 1
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#task 2
arr = np.arange(9)
matrix_3x3 = arr.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#task 3
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#task 4
random_array = np.random.random(30)
print("Random Array:", random_array)
mean_value = random_array.mean()
print("Mean of the array:", mean_value)

Random Array: [0.95831612 0.52616354 0.54033212 0.04510716 0.00459358 0.66131581
 0.81786246 0.50336494 0.31893248 0.62457514 0.73438279 0.18657712
 0.64768955 0.89831192 0.59508347 0.26607078 0.82484018 0.94396652
 0.33560313 0.59493001 0.07082712 0.84386019 0.36909637 0.62937294
 0.49667115 0.90430528 0.31591047 0.49333544 0.77599192 0.66359813]
Mean of the array: 0.5530329277956405


In [ ]:
#task 5
random_array = np.random.random((10, 10))
print("Random 10x10 Array:\n", random_array)
min_value = random_array.min()
max_value = random_array.max()
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 Array:
 [[0.77941137 0.73074461 0.43813022 0.66056873 0.40022331 0.48415654
  0.42013681 0.10303491 0.76861548 0.49301376]
 [0.05427375 0.79634539 0.36945834 0.20076701 0.62511208 0.05539478
  0.99009932 0.25972862 0.93906563 0.48942398]
 [0.0360974  0.77011565 0.08621446 0.3360977  0.55166979 0.58159996
  0.14607435 0.94694034 0.23814188 0.28024113]
 [0.88662799 0.822639   0.87104617 0.57614819 0.57987074 0.7384537
  0.20032133 0.84164796 0.88718323 0.71023494]
 [0.40085835 0.16162772 0.38191298 0.3639292  0.18738003 0.1415014
  0.15827531 0.15023924 0.62528561 0.68854881]
 [0.0731633  0.63175333 0.45213883 0.50195256 0.48772543 0.63122044
  0.98332063 0.84452278 0.75816674 0.18907416]
 [0.2364711  0.53853906 0.36757409 0.43823971 0.12169354 0.58056378
  0.61577118 0.45822622 0.39419208 0.38763044]
 [0.86721842 0.03252327 0.76504883 0.49470881 0.48329441 0.42236679
  0.35565511 0.94675554 0.74688482 0.60204096]
 [0.32407444 0.01017446 0.45569037 0.34385395 0.26128786 0.01

In [ ]:
#task 6
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#task 7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
#task 8
rows, cols = 5, 5
arr = np.ones((rows, cols))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#task 9
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [ ]:
#task 1
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add the 2D arrays
sum_xy = x + y
print("Sum of x and y:\n", sum_xy)

# Add the 1D arrays
sum_vw = v + w
print("Sum of v and w:\n", sum_vw)

Sum of x and y:
 [[ 6  8]
 [10 13]]
Sum of v and w:
 [20 22]


In [ ]:
#task 2
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Subtract the 2D arrays
diff_xy = x - y
print("Subtraction of x and y:\n", diff_xy)

# Subtract the 1D arrays
diff_vw = v - w
print("Subtraction of v and w:\n", diff_vw)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Subtraction of v and w:
 [-2 -2]


In [ ]:
#task 3
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

mult_x = x * 3
mult_y = y * 2
mult_v = v * 5
mult_w = w * 4

print("x multiplied by 3:\n", mult_x)
print("y multiplied by 2:\n", mult_y)
print("v multiplied by 5:\n", mult_v)
print("w multiplied by 4:\n", mult_w)

x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
y multiplied by 2:
 [[10 12]
 [14 16]]
v multiplied by 5:
 [45 50]
w multiplied by 4:
 [44 48]


In [ ]:
#task 4
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

square_x = x ** 2
square_y = np.square(y)
square_v = v ** 2
square_w = np.square(w)

print("Square of x:\n", square_x)
print("Square of y:\n", square_y)
print("Square of v:\n", square_v)
print("Square of w:\n", square_w)

Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v:
 [ 81 100]
Square of w:
 [121 144]


In [ ]:
#task 5
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
#task 6
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_xy_rows)

v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_vw_col = np.concatenate((v_col, w_col), axis=1)
print("Concatenate v and w along columns:\n", concat_vw_col)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
#task 7
x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


An error occurs because x is a 2D array and v is a 1D array. NumPy cannot concatenate arrays with different dimensions. Converting v into a 2D array allows the concatenation to work.

Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])
I = np.eye(2)

In [ ]:
#task 1
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print("A * A_inv =\n", result)

A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#task 2
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA ? False


In [ ]:
#task 3
AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", B_TA_T)
print("Equal?", np.array_equal(AB_T, B_TA_T))

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Equal? True


In [ ]:
#linear equation
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)

print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

In [ ]:
import numpy as np
import time

In [ ]:
#task 1
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
end_time = time.time()

print("Python list addition took:", end_time - start_time, "seconds")

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()

print("NumPy array addition took:", end_time - start_time, "seconds")

Python list addition took: 0.0849308967590332 seconds
NumPy array addition took: 0.004065513610839844 seconds


In [ ]:
#task 2
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

print("Python list multiplication took:", end_time - start_time, "seconds")

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_time = time.time()
result_array = arr1 * arr2
end_time = time.time()

print("NumPy array multiplication took:", end_time - start_time, "seconds")

Python list multiplication took: 0.10661458969116211 seconds
NumPy array multiplication took: 0.002140522003173828 seconds


In [ ]:
#task 3
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start_time = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()

print("Python list dot product took:", end_time - start_time, "seconds")

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_time = time.time()
dot_array = np.dot(arr1, arr2)
end_time = time.time()

print("NumPy array dot product took:", end_time - start_time, "seconds")

Python list dot product took: 0.09236907958984375 seconds
NumPy array dot product took: 0.001895904541015625 seconds


In [ ]:
#task 4
size = 500
mat1 = [[i + j for j in range(size)] for i in range(size)]
mat2 = [[i - j for j in range(size)] for i in range(size)]

start_time = time.time()
result_list = [[0 for _ in range(size)] for _ in range(size)]
for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += mat1[i][k] * mat2[k][j]

end_time = time.time()
print("Python list matrix multiplication took:", end_time - start_time, "seconds")

arr1 = np.arange(size*size).reshape(size, size)
arr2 = np.arange(size*size).reshape(size, size)

start_time = time.time()
result_array = np.dot(arr1, arr2)
end_time = time.time()

print("NumPy array matrix multiplication took:", end_time - start_time, "seconds")

Python list matrix multiplication took: 49.23273825645447 seconds
NumPy array matrix multiplication took: 0.275515079498291 seconds
